.eslintrc, .github/pull_request_template.md, .github/workflows/lint.yaml, .github/workflows/tests.yaml, README.md, WRITING_INTEGRATION_SCRIPTS.md, package-lock.json, package.json
Updates the linting package to use the remote one
NAN-1760
=> fix(templates): [nan-1760] update lint package and documentation

.github/workflows/deploy-scripts-internally.yaml
=> fix(integration-templates): install nango from root

.github/workflows/deploy-scripts-internally.yaml
=> fix(gh-actions): add debug

.github/workflows/deploy-scripts-internally.yaml
=> fix(gh-action): deployment logic

.github/workflows/deploy.yaml
Don't upload to `integrations`
=> fix(s3-upload): fix upload location

.github/workflows/deploy.yaml, scripts/compile-all-templates.bash, scripts/generate-integration-template-zod.bash
=> fix(s3-upload): include zod schema file

.github/workflows/deploy.yaml
=> fix(s3-upload): typo fix

.github/workflows/push-flows-to-nango-repo.yaml, flows.yaml, integrations/hubspot/nango.yaml
Fix delete description and debug output for push to nango repo
=> fix(hubspot): Fix hubspot description for delete action

.github/workflows/push-flows-to-nango-repo.yaml
=> fix(gh-action): commit info

flows.yaml, integrations/hubspot/nango.yaml
=> fix(groups): fix spelling error

integrations/google-drive/syncs/documents.md, integrations/linkedin/actions/post.ts
-   [x] I added tests, otherwise the reason is:
-   [x] External API requests have `retries`
-   [x] Pagination is used where appropriate
-   [x] The built in `nango.paginate` call is used instead of a `while (true)` loop
-   [x] Third party requests are NOT parallelized (this can cause issues with rate limits)
-   [x] I followed the best practices and guidelines from the [Writing Integration Scripts](/NangoHQ/integration-templates/blob/main/WRITING_INTEGRATION_SCRIPTS.md) doc
=> feat(linkedin): migrate helper logic to action

LICENSE, LICENSE_SHORT
=> fix(license): add license

package-lock.json, package.json
=> chore(nango-cli): bump nango cli

flows.yaml, integrations/airtable/actions/whoami.md, integrations/airtable/actions/whoami.ts, integrations/airtable/nango.yaml, integrations/airtable/types.ts, integrations/hubspot/actions/whoami.md, integrations/hubspot/actions/whoami.ts, integrations/hubspot/nango.yaml, integrations/hubspot/types.ts
=> feat(whoami): whoami for hubspot and airtable

integrations/avalara-sandbox/schema.zod.ts
=> fix(templates): update symlink

flows.yaml, integrations/workday/mappers/jobFamilyToGroup.ts, integrations/workday/mappers/locationToLocation.ts, integrations/workday/mappers/workerToEmployee.ts, integrations/workday/nango.yaml, integrations/workday/syncs/employees.md, integrations/workday/syncs/employees.ts, integrations/workday/syncs/groups.md, integrations/workday/syncs/groups.ts, integrations/workday/syncs/locations.md, integrations/workday/syncs/locations.ts, integrations/workday/types.ts, integrations/workday/utils.ts, package-lock.json, package.json
=> feat(workday): add workday syncs

flows.yaml, integrations/smartsheet/actions/create-user.md, integrations/smartsheet/actions/delete-user.md, integrations/smartsheet/actions/disable-user.md, integrations/smartsheet/nango.yaml, integrations/smartsheet/syncs/users.md
=> fix(smartsheet): Add scopes

flows.yaml, integrations/netsuite-tba/helpers/utils.ts, integrations/netsuite-tba/nango.yaml, integrations/netsuite-tba/syncs/credit-notes.md, integrations/netsuite-tba/syncs/credit-notes.ts, integrations/netsuite-tba/syncs/customers.md, integrations/netsuite-tba/syncs/customers.ts, integrations/netsuite-tba/syncs/general-ledger.md, integrations/netsuite-tba/syncs/general-ledger.ts, integrations/netsuite-tba/syncs/invoices.md, integrations/netsuite-tba/syncs/invoices.ts, integrations/netsuite-tba/syncs/locations.md, integrations/netsuite-tba/syncs/locations.ts, integrations/netsuite-tba/syncs/payments.md, integrations/netsuite-tba/syncs/payments.ts
=> feat(netsuite): update syncs to incremental

WRITING_INTEGRATION_SCRIPTS.md
Add guideline on best practices for handling date inputs
=> feat(docs): add best practice for validating date inputs

flows.yaml, integrations/gorgias/actions/create-user.md, integrations/gorgias/nango.yaml
=> fix(gorgias): Fix endpoint

.github/workflows/deploy-scripts-internally.yaml, .github/workflows/deploy.yaml
=> fix(deploy): dynamic nature of the nango.yaml

.github/workflows/deploy-scripts-internally.yaml, .github/workflows/deploy.yaml, integrations/bill-sandbox/schema.zod.ts
=> fix(deploy): Proper fix deploy

integrations/docusign-sandbox/schema.zod.ts, integrations/quickbooks-sandbox/schema.zod.ts
=> fix(deploy): add symlinks

.cursor/rules/nango-script-best-practices.yaml, .cursor/rules/typescript-development-guidelines-shortcuts.mdc, .eslintignore, .husky/pre-commit, README.md, WRITING_INTEGRATION_SCRIPTS.md, coderabbit.template.yaml, scripts/code-rabbit-yaml.ts, scripts/cursor-rules.ts
=> feat(testing-ai): Testing instructions

integrations/bitdefender/actions/get-company-details.ts
=> fix(bitdefender): Update get-company-details.ts

.cursor/rules/nango-script-best-practices.mdc, WRITING_INTEGRATION_SCRIPTS.md, rules-for-custom-nango-integrations/nango-best-practices.mdc, scripts/cursor-rules-for-custom-integrations.ts
=> fix(docs): small tweaks

rules-for-custom-nango-integrations/README.md
=> feat(docs): add mcp usage info

.cursor/rules/nango-script-best-practices.mdc, .husky/pre-commit, ADVANCED_INTEGRATION_SCRIPT_PATTERNS.md, rules-for-custom-nango-integrations/nango-best-practices.mdc, scripts/cursor-rules-for-custom-integrations.ts, scripts/cursor-rules.ts
=> feat(advanced-rules): More instructions

flows.yaml, integrations/github-app-oauth/actions, integrations/github-app-oauth/constants.ts, integrations/github-app-oauth/fields.ts, integrations/github-app-oauth/graphql, integrations/github-app-oauth/helpers, integrations/github-app-oauth/mappers, integrations/github-app-oauth/nango.yaml, integrations/github-app-oauth/schema.zod.ts, integrations/github-app-oauth/syncs, integrations/github-app-oauth/types.ts, integrations/github-app/nango.yaml
Add symlink for `github-app-oauth`
=> feat(github-app-oauth): add symlink

integrations/gong-oauth/helpers
- fix(gong-oauth): broken symlink
This folder does not exists anymore apparently
=> fix(gong-oauth): broken symlink

.github/workflows/deploy.yaml
=> fix(s3): template upload
