.github/workflows/push-flows-to-nango-repo.yaml

When the `flows.yaml` file changes push it to the `nango` repo so that the file is always up to date. I opted for a Github Action because that seem more fitting to the purposes of a Github App rather than a separate bot user. Additionally a Github App can have special bypass permissions
NAN-1761

feat(flows.yaml): [nan-1761] add github app push

---

flows.yaml
integrations/anrok/nango.yaml
integrations/asana/nango.yaml

Update endpoints to be more standard

fix(endpoints): endpoint updates

---

.github/workflows/push-flows-to-nango-repo.yaml

fix(gh-action): add gh token

---

flows.yaml
integrations/ashby/nango.yaml

fix(endpoints): ashby endpoints

---

flows.yaml
integrations/bamboohr-basic/nango.yaml

fix(bamboo-yaml): update bamboo endpoints

---

flows.yaml
integrations/clari-copilot/nango.yaml

fix(endpoint): clari endpoint update

---

flows.yaml
integrations/confluence/nango.yaml

fix(endpoints): update confluence

---

flows.yaml
integrations/discourse/nango.yaml

fix(endpoint): discourse endpoint

---

.husky/pre-commit
scripts/generate-integration-template-tests.bash

chore(templates): add command and export upgrade ignore

---

flows.yaml
integrations/google-mail/nango.yaml
integrations/google-mail/syncs/emails.ts

fix(gmail-template): [nan-1846] optional check

---

flows.yaml
integrations/notion/actions/fetch-database.ts
integrations/notion/mocks/fetch-database/output.json
integrations/notion/mocks/nango/get/proxy/v1/databases/111ce298-3121-802a-8889-e03a52fcc04e/fetch-database.json
integrations/notion/mocks/nango/post/proxy/v1/databases/111ce298-3121-802a-8889-e03a52fcc04e/query/fetch-database.json
integrations/notion/nango.yaml

Output the row id with the row data for notion. Clarify the description

fix(notion-db-action): add id of the row in the output

---

integrations/bill/actions/create-user.ts

fix(docs): doc link

---

flows.yaml
integrations/outlook/nango.yaml

BUmp version, remove sender as required.

fix(outlook): version bump

---

.husky/pre-commit
flows.yaml
integrations/xero/nango.yaml
scripts/generate-integration-template-tests.bash

- Fix endpoints
- Update precommit script to only operate on changed files

fix(xero): Fix xero endpoints & tweak precommit script to generate tests

---

flows.yaml
integrations/salesforce/nango.yaml

fix(salesforce): update endpoints and bump versions

---

flows.yaml
integrations/google-drive/nango.yaml
integrations/google-drive/syncs/documents.ts

Ensure all files can be fetched
NAN-2004

fix(drive): supportsAllDrives option

---

flows.yaml
integrations/google-drive/actions/fetch-document.ts
integrations/google-drive/nango.yaml

fix(g-drive): add includeAllDrives query param

---

package.json
scripts/run-integration-template.bash

If an .env file is added with these contents:
```
NANGO_SECRET_KEY_DEV=aaa-aaa-aaa
NANGO_HOSTPORT=https://api.nango.dev
```
You can now just run 
```
npm run dryrun -- datadog users d
```
The pattern above being `dryrun $INTEGRATION $SCRIPT_NAME $CONNECTION_NAME`
Instead of 
```
bash scripts/run-integration-template.bash KEY=aaa-aaa-aaa HOST=https://api.nango.dev datadog dryrun users d
```
Note that this is backwards compatible

feat(tooling): simplify dryrun command

---

flows.yaml
integrations/okta-preview/actions
integrations/okta-preview/mappers
integrations/okta-preview/nango.yaml
integrations/okta-preview/schema.zod.ts
integrations/okta-preview/syncs
integrations/okta-preview/types.ts

Add syncs and actions to okta-preview
NAN-2124

feat(okta): [nan-2124] add in okta preview

---

flows.yaml
integrations/harvest/nango.yaml
integrations/harvest/syncs/users.ts

Harvest has an `updated_since` param

fix(harvest): incremental sync for harvest users

---

flows.yaml
integrations/slack/actions/send-message.ts
integrations/slack/mappers/to-message.ts
integrations/slack/nango.yaml
integrations/slack/syncs/users.ts

fix(slack): typo

---

flows.yaml
integrations/quickbooks-sandbox/nango.yaml

fix(groups): backfill quickbooks sandbox

---

integrations/zoom/syncs/meetings.ts

fix(docs): fix zoom endpoint

---

flows.yaml
integrations/ashby/nango.yaml

- update nango.yaml to match
```
path: /candidates
group: Candidates
```

fix(ashby): update nango.yaml

---

integrations/netsuite-tba/actions/credit-note-create.ts
integrations/netsuite-tba/actions/customer-create.ts
integrations/netsuite-tba/actions/invoice-create.ts
integrations/netsuite-tba/actions/payment-create.ts

Use different notation to access

fix(netsuite): header access

---

flows.yaml
integrations/lever/actions/create-opportunity.ts
integrations/lever/nango.yaml

fix(lever): more cleanup of endpoints

---

flows.yaml
integrations/front/nango.yaml
integrations/front/syncs/list-conversations.ts

- Small fix to Front's `list-conversations` pagination

fix(front): add cursor in request param for pagination

---

flows.yaml
integrations/lever/nango.yaml

fix(lever): fix typo

---

flows.yaml
integrations/xero/actions/get-tenants.ts
integrations/xero/helpers/get-tenant-id.ts
integrations/xero/nango.yaml

Add in logic to use the metadata for the chosen tenant id

fix(xero): add tenant id logic

---

flows.yaml
integrations/xero/nango.yaml

fix(xero): bump versions

---

flows.yaml
integrations/google-drive/nango.yaml

to make mintlify happy
For the docs updates in the other repo, Mintlify really doesn't like this drive description having curly braces in it, so I'm making it code to fix the issue up.
-   [ ] I followed the best practices and guidelines from the [Writing Integration Scripts](/NangoHQ/integration-templates/blob/main/WRITING_INTEGRATION_S …

chore: Fix up google drive sync description

---

integrations/asana/actions/delete-task.md
integrations/checkr-partner/actions/create-candidate.md
integrations/google-drive/syncs/documents.md
integrations/google/syncs/workspace-org-units.md
integrations/google/syncs/workspace-user-access-tokens.md
integrations/google/syncs/workspace-users.md
scripts/generate-readmes.ts

Fixes up our readme generator to not show anything after description if it's unset in the nango.yaml. Also adds a warning so they're easier to spot.

fix: Readme descriptions that say undefined because they're empty

---

vitest.setup.ts

The first page wasn't including a limit param, and that caused issues for tests.

fix(test): Set limit on first page

---

flows.yaml
integrations/notion/actions/fetch-content-metadata.md
integrations/notion/actions/fetch-database.md
integrations/notion/actions/fetch-rich-page.md
integrations/notion/nango.yaml
integrations/notion/syncs/content-metadata.md
integrations/notion/syncs/databases.md

fix(notion): tweak yaml

---

flows.yaml
integrations/linkedin/actions/post.md
integrations/linkedin/nango.yaml

See https://linear.app/nango/issue/NAN-2434/undefined-undefined-endpoint-in-docs

fix(linkedin): Fix endpoint for linkedin

---

.github/workflows/tests.yaml

I just noticed that our test script was set to run on `master` but not on `main`.

fix(ci): Run tests on main branch

---

flows.yaml
integrations/linear/actions/create-issue.md
integrations/linear/actions/create-issue.ts
integrations/linear/fields/issue.ts
integrations/linear/nango.yaml

fix(linear): add project milestone and mapping logic

---

flows.yaml
integrations/calendly/actions/whoami.md
integrations/calendly/actions/whoami.ts
integrations/calendly/nango.yaml
integrations/salesforce/actions/whoami.md
integrations/salesforce/actions/whoami.ts
integrations/salesforce/nango.yaml
integrations/salesforce/types.ts
integrations/zoom/actions/whoami.md
integrations/zoom/actions/whoami.ts
integrations/zoom/nango.yaml

Adds whoami endpoints for a few APIs for consistency

feat(whoami): Add whoami endpoints

---

flows.yaml
integrations/smartsheet/actions/create-user.ts
integrations/smartsheet/nango.yaml

fix(smartsheet): small model tweaks

---

integrations/jira/syncs/projects.ts

Jira has a pagination issue with a limit over 50

fix(jira): reduce pagination to 50

---

flows.yaml
integrations/netsuite-tba/nango.yaml
integrations/netsuite-tba/syncs/locations.md
integrations/netsuite-tba/syncs/locations.ts

update netsuite-tba locations sync to handle optional timeZone reference

fix(netsuite-tba): handle optional timeZone reference in location sync

---

flows.yaml
integrations/linear/actions/create-issue.ts
integrations/linear/nango.yaml
integrations/linear/syncs/users.md
integrations/linear/syncs/users.ts

feat(linear): add users sync

---

flows.yaml
integrations/google-drive/actions/fetch-document.md
integrations/google-drive/actions/fetch-document.ts
integrations/google-drive/nango.yaml

Take in an object instead of a string

fix(google-drive): id should be an object

---

flows.yaml
integrations/intercom/actions/whoami.md
integrations/intercom/actions/whoami.ts
integrations/intercom/nango.yaml
integrations/intercom/types.ts

feat(whoami): add whoami endpoint for intercom

---

flows.yaml
integrations/calendly/nango.yaml
integrations/calendly/syncs/events.md
integrations/jira/helpers/get-cloud-data.ts

fix(optionals): chaining

---

flows.yaml
integrations/basecamp/nango.yaml
integrations/basecamp/syncs/todos.md

We were seeing a mintlify error in the main repo because it doesn't like inline json

fix: Update basecamp docs to fix mintlify error

---

integrations/avalara/syncs/transactions.md
integrations/basecamp/syncs/todos.md
integrations/dropbox/syncs/files.md
integrations/github/syncs/list-files.md
integrations/google-drive/syncs/documents.md
integrations/google-mail/syncs/emails.md
integrations/google/syncs/workspace-users.md
integrations/jira/syncs/issue-types.md
integrations/jira/syncs/issues.md
integrations/microsoft-teams/syncs/users.md
integrations/outlook/syncs/emails.md
integrations/salesforce/syncs/articles.md
integrations/sharepoint-online/syncs/shared-sites-selection.md
integrations/sharepoint-online/syncs/user-files-selection.md
integrations/zoom/syncs/recording-files.md
scripts/generate-readmes.ts

Adds expected metadata segment to readmes
See https://linear.app/nango/issue/NAN-2639/add-input-type-info-to-syncs

feat: Add sync input info to readmes

---

flows.yaml
integrations/basecamp/actions/fetch-accounts.md
integrations/basecamp/actions/fetch-accounts.ts
integrations/basecamp/nango.yaml
integrations/basecamp/types.ts

Added so that our users can show an option for their users to select a particular account

feat(basecamp): add action to do a user lookup

---

flows.yaml
integrations/recharge/mappers/to-customer.ts
integrations/recharge/nango.yaml
integrations/recharge/syncs/customers.md

feat(recharge): add email

---

flows.yaml
integrations/hubspot/actions/fetch-properties.md
integrations/hubspot/nango.yaml

fix(scopes): add more explicit scopes

---

flows.yaml
integrations/brightcrowd/syncs/book-analytics.md
integrations/brightcrowd/syncs/books-by-id.md
integrations/brightcrowd/syncs/books.md
integrations/brightcrowd/syncs/pages.md
integrations/google-drive/nango.yaml
integrations/google-drive/syncs/documents.md
integrations/google-drive/syncs/documents.ts

feat(google-drive): output the mimeType

---

integrations/aircall-basic/.nango

fix(aircall): add missing symlink directory

---

scripts/run-integration-template.bash

Add dereference flag to copy(cp) command to ensure symbolic links are followed when running script in linux environments

fix(integration): always dereference symbolic links when copying files

---

flows.yaml
integrations/confluence/nango.yaml
integrations/confluence/syncs/pages.md
integrations/confluence/syncs/pages.ts
integrations/confluence/types.ts

fix(confluence): confluence type issue

---

flows.yaml
integrations/basecamp/actions/create-todo.md
integrations/basecamp/actions/fetch-projects.md
integrations/basecamp/actions/fetch-todolists.md
integrations/basecamp/nango.yaml
integrations/basecamp/syncs/todos.md

fix(basecamp): bump versions

---

flows.yaml
integrations/basecamp/nango.yaml
integrations/basecamp/syncs/todos.md
integrations/basecamp/syncs/todos.ts

- Due date comes back as null in some cases. 
- Ensure that ids are a string, not a number

fix(basecamp-types): type fixes

---

flows.yaml
integrations/google-calendar/nango.yaml
integrations/google-calendar/syncs/events.md

fix(g-cal): tighten up types

---

integrations/workday/syncs/locations.ts

fix(workday): missing model

---

flows.yaml
integrations/microsoft-teams/nango.yaml
integrations/microsoft-teams/syncs/org-units.md
integrations/microsoft-teams/syncs/org-units.ts
integrations/microsoft-teams/syncs/users.md
integrations/microsoft-teams/syncs/users.ts

Fix pagination and null objects

fix(microsoft-teams): fix pagination and org unit

---

integrations/keeper-scim/actions/create-user.ts
integrations/zoom/actions/create-user.ts

fix(compilation): remove schema usage

---

flows.yaml
integrations/hubspot/actions/fetch-properties.md
integrations/hubspot/nango.yaml

fix(hubspot): clean up typing

---

flows.yaml
integrations/hubspot/.nango/schema.json
integrations/hubspot/.nango/schema.ts
integrations/hubspot/actions/fetch-properties.md
integrations/hubspot/nango.yaml

fix(schema): bump the version

---

integrations/box/actions/folder-content.ts

fix(types): clean up types

---

.coderabbit.yaml

feat(reviews): add code rabbit config

---

.cursor/rules/nango-script-best-practices.mdc
ADVANCED_INTEGRATION_SCRIPT_PATTERNS.md
rules-for-custom-nango-integrations/nango-best-practices.mdc

fix(docs): batch save instead of return

---

integrations/gusto/syncs/employees.ts

fix(types): compilation issue

---

.coderabbit.yaml
.cursor/rules/nango-script-best-practices.mdc
flows.yaml
guides/WRITING_SCRIPTS.md
guides/rules-for-custom-nango-integrations/nango-best-practices.mdc
integrations/dropbox/.nango/schema.json
integrations/dropbox/.nango/schema.ts
integrations/dropbox/actions/folder-content.md
integrations/dropbox/actions/folder-content.ts
integrations/dropbox/nango.yaml
integrations/google-drive/.nango/schema.json
integrations/google-drive/.nango/schema.ts
integrations/google-drive/actions/fetch-document.md
integrations/google-drive/actions/folder-content.md
integrations/google-drive/actions/folder-content.ts
integrations/google-drive/actions/list-drives.md
integrations/google-drive/actions/list-drives.ts
integrations/google-drive/nango.yaml
integrations/google-drive/syncs/documents.md
integrations/google-drive/syncs/folders.md

fix(cursor): Fix cursor and document

---

.cursor/rules/nango-script-best-practices.mdc
guides/ADVANCED_INTEGRATION_SCRIPT_PATTERNS.md
guides/WRITING_CUSTOM_INTEGRATION_SCRIPTS.md
guides/rules-for-custom-nango-integrations/nango-best-practices.mdc

fix(type-references): add more info about the models.ts file and fix references

---

.cursor/rules/nango-script-best-practices.mdc
guides/ADVANCED_INTEGRATION_SCRIPT_PATTERNS.md
guides/rules-for-custom-nango-integrations/nango-best-practices.mdc

feat(more-guides): finish up guides

---

.cursor/rules/nango-script-best-practices.mdc
guides/ADVANCED_INTEGRATION_SCRIPT_PATTERNS.md
guides/rules-for-custom-nango-integrations/nango-best-practices.mdc

docs(multi-model): add guidance on a multi model sync

---

flows.yaml
integrations/recruiterflow/actions/candidate-activities-list.md
integrations/recruiterflow/actions/candidate-activities-stage-movements.md
integrations/recruiterflow/actions/candidate-scorecards.md
integrations/recruiterflow/actions/job-pipelines.md
integrations/recruiterflow/nango.yaml
integrations/recruiterflow/syncs/candidate-activity-types.md
integrations/recruiterflow/syncs/candidates.md
integrations/recruiterflow/syncs/employment-types.md
integrations/recruiterflow/syncs/job-departments.md
integrations/recruiterflow/syncs/job-remote-statuses.md
integrations/recruiterflow/syncs/job-stage-names.md
integrations/recruiterflow/syncs/job-statuses.md
integrations/recruiterflow/syncs/jobs.md
integrations/recruiterflow/syncs/locations.md
integrations/recruiterflow/syncs/organization-locations.md
integrations/recruiterflow/syncs/users.md

fix(groups): Fix recruiter groups

---

flows.yaml
integrations/slack/nango.yaml
integrations/slack/syncs/messages.md
integrations/slack/syncs/messages.ts

This PR addresses an issue in the Slack messages sync where messages were being unnecessarily marked as updated on every run. This was caused by the `block_id` field in the Slack API response, which is not stable and can change between
API calls.
To resolve this, we now remove the `block_id` from the message and reply payloads before they are stringified and saved to the `raw_json` field.
-   **Removed `block_id` from `raw_json`**: Implemented logic to recursively find and delete the `block_id` from the `blocks` array, whether it's at the top level or nested within `attachments`.
[EXT-748](https://linear.app/nango/issue/EXT-748/update-slack-messages-template-to-remove-block-id)
-   [ ] Pagination …

chore(slack): add removeBlockIds function to clean message data

---

flows.yaml
integrations/xero/.nango/nango.json
integrations/xero/nango.yaml
integrations/xero/syncs/bank-transactions.md

fix(xero): cleanup endpoint

---

.github/workflows/deploy.yaml

fix(templates): use the correct directory

---

.github/workflows/deploy.yaml

fix(deploy): skip proxy only integrations

---

.github/workflows/deploy.yaml
internal/scripts/resolve-aliases.ts

fix(s3-deploy): resolve alises
